<h1>Strings in Python</h1>

In [1]:
# Define a string
my_string = "Hello, world!"

# Print the string
print(my_string)

# Accessing characters in the string
first_char = my_string[0]
last_char = my_string[-1]
print("First character:", first_char)
print("Last character:", last_char)

# Slicing the string
substring = my_string[7:12]
print("Substring:", substring)

# Convert the string to uppercase
uppercase_string = my_string.upper()
print("Uppercase:", uppercase_string)

# Convert the string to lowercase
lowercase_string = my_string.lower()
print("Lowercase:", lowercase_string)

Hello, world!
First character: H
Last character: !
Substring: world
Uppercase: HELLO, WORLD!
Lowercase: hello, world!


<h1>Data Types in Python</h1>

In [2]:
# Integer
my_int = 42
print("Integer:", my_int)

# Float
my_float = 3.14
print("Float:", my_float)

# String
my_string = "Hello, world!"
print("String:", my_string)

# Boolean
my_bool = True
print("Boolean:", my_bool)

# List
my_list = [1, 2, 3, 4, 5]
print("List:", my_list)

# Tuple
my_tuple = (1, 2, 3, 4, 5)
print("Tuple:", my_tuple)

# Dictionary
my_dict = {"name": "Alice", "age": 30}
print("Dictionary:", my_dict)

Integer: 42
Float: 3.14
String: Hello, world!
Boolean: True
List: [1, 2, 3, 4, 5]
Tuple: (1, 2, 3, 4, 5)
Dictionary: {'name': 'Alice', 'age': 30}


<h1>Loops in Python</h1>

In [3]:
# For loop
for i in range(5):
    print(i)

# While loop
counter = 0
while counter < 5:
    print(counter)
    counter += 1

0
1
2
3
4
0
1
2
3
4


<h1>Conditional Statement in Python</h1>

In [4]:
# Define a variable
x = 10

# Conditional statement
if x > 5:
    print("x is greater than 5")
else:
    print("x is not greater than 5")

# If-elif-else Statement:
x = 5
if x > 0:
    print("x is positive")
elif x < 0:
    print("x is negative")
else:
    print("x is zero")

# Nested If Statement:
x = 5
if x > 0:
    if x % 2 == 0:
        print("x is positive and even")
    else:
        print("x is positive and odd")
else:
    print("x is not positive")

x is greater than 5
x is positive
x is positive and odd


<h1>Functions in Python</h1>

In [8]:
# Define a function
def greet(name):
    """Greets the user."""
    print("Hello, " + name + "!")

# Call the function
greet("Alice")
greet("Bob")

#Recursive Function:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

print(factorial(7))

Hello, Alice!
Hello, Bob!
5040


<h1>Classes in Python</h1>

In [10]:
# Define a simple class
class Dog:
    # Constructor
    def __init__(self, name, age):
        self.name = name
        self.age = age

    # Method to bark
    def bark(self):
        print("Woof!")

# Create an instance of the Dog class
my_dog = Dog("Buddy", 3)

# Access attributes and call methods
print("Name:", my_dog.name)
print("Age:", my_dog.age)
my_dog.bark()

Name: Buddy
Age: 3
Woof!


<h1>NumPy Library in Python</h1>

NumPy is a Python library for numerical computing, offering efficient arrays and mathematical functions, crucial for tasks like data analysis and scientific computing. NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

In [11]:
import numpy as np
arr1 = np.array([13, 15, 11, 14, 12])
print(arr1)

# Functions in NUmpy
arr = np.zeros(2)
print(arr)
arr = np.ones(2)
print(arr)
empty_arr = np.empty(2)
empty_arr[0] = 17
empty_arr[1] = 16
print(empty_arr)
print(np.sort(arr1))
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(np.concatenate((a, b)))

[13 15 11 14 12]
[0. 0.]
[1. 1.]
[17. 16.]
[11 12 13 14 15]
[1 2 3 4 5 6 7 8]


<h1>pandas Library in Python</h1>

Pandas is a Python library for data manipulation and analysis, featuring easy-to-use data structures like DataFrame and Series, ideal for tasks such as cleaning, transforming, and analyzing structured data. Pandas is used for data manipulation and analysis, offering powerful data structures and tools for working with structured data. Overall, Pandas is widely used by data scientists, analysts, and developers for data exploration, cleaning, preprocessing, and analysis tasks, making it an essential tool in the Python ecosystem for working with structured data.

<h2>Managing Datasets using pandas</h2>

<h3>Dataset: salaries</h3>

In [12]:
import pandas as pd
# Reading Data from CSV File:
df = pd.read_csv('salaries.csv')
print(df.head())

   work_year experience_level employment_type            job_title  salary  \
0       2024               SE              FT  Security Consultant   75000   
1       2024               SE              FT  Security Consultant   55000   
2       2024               SE              FT    Security Engineer  230000   
3       2024               SE              FT    Security Engineer  168000   
4       2024               SE              FT    Security Engineer  230000   

  salary_currency  salary_in_usd employee_residence  remote_ratio  \
0             GBP          93750                 GB             0   
1             GBP          68750                 GB             0   
2             USD         230000                 US             0   
3             USD         168000                 US             0   
4             USD         230000                 US             0   

  company_location company_size  
0               GB            M  
1               GB            M  
2             

In [13]:
print(df.tail())


      work_year experience_level employment_type  \
5298       2020               MI              FT   
5299       2021               SE              FT   
5300       2021               SE              FT   
5301       2021               MI              FT   
5302       2021               MI              FT   

                         job_title  salary salary_currency  salary_in_usd  \
5298        Cyber Security Analyst  140000             AUD          96422   
5299  Information Security Manager   60000             GBP          82528   
5300  Penetration Testing Engineer  126000             USD         126000   
5301  Information Security Analyst   42000             GBP          57769   
5302   Threat Intelligence Analyst   66310             USD          66310   

     employee_residence  remote_ratio company_location company_size  
5298                 AU            50               AU            M  
5299                 GB            50               GB            L  
5300          

In [14]:
# Basic DataFrame Operations:
print(df.shape)
print(df.columns)
print(df.describe())
print(df['experience_level'])

(5303, 11)
Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')
         work_year        salary  salary_in_usd  remote_ratio
count  5303.000000  5.303000e+03    5303.000000   5303.000000
mean   2022.541580  3.662708e+05  146160.636621     41.900811
std       0.819484  1.072331e+07   63919.548433     47.820549
min    2020.000000  1.640000e+04   15897.000000      0.000000
25%    2022.000000  1.004750e+05  100000.000000      0.000000
50%    2023.000000  1.400000e+05  138000.000000      0.000000
75%    2023.000000  1.830000e+05  180000.000000    100.000000
max    2024.000000  6.000000e+08  700000.000000    100.000000
0       SE
1       SE
2       SE
3       SE
4       SE
        ..
5298    MI
5299    SE
5300    SE
5301    MI
5302    MI
Name: experience_level, Length: 5303, dtype: object


<h3>Dataset: Cyber Security</h3>

In [15]:
# Reading Data from CSV File:
df1 = pd.read_csv('dataset_cybersecurity_michelle.csv')
print(df1.head())

   qty_dot_url  qty_hyphen_url  qty_underline_url  qty_slash_url  \
0            1               0                  0              1   
1            2               5                  4              2   
2            2               0                  0              0   
3            1               1                  0              2   
4            2               1                  0              0   

   qty_questionmark_url  qty_equal_url  qty_at_url  qty_and_url  \
0                     0              0           0            0   
1                     0              0           0            0   
2                     0              0           0            0   
3                     0              0           0            0   
4                     0              0           0            0   

   qty_exclamation_url  qty_space_url  ...  qty_ip_resolved  qty_nameservers  \
0                    0              0  ...                2                2   
1                    0      

In [16]:
print(df1.tail())


        qty_dot_url  qty_hyphen_url  qty_underline_url  qty_slash_url  \
129693            3               1                  0              0   
129694            2               0                  0              0   
129695            2               1                  0              5   
129696            2               0                  0              1   
129697            2               0                  0              0   

        qty_questionmark_url  qty_equal_url  qty_at_url  qty_and_url  \
129693                     0              0           0            0   
129694                     0              0           0            0   
129695                     0              0           0            0   
129696                     0              0           0            0   
129697                     0              0           0            0   

        qty_exclamation_url  qty_space_url  ...  qty_ip_resolved  \
129693                    0              0  ...             

In [17]:
# Basic DataFrame Operations:
print(df1.shape)
print(df1.columns)
print(df1.describe())
print(df1['qty_dot_url'])

(129698, 112)
Index(['qty_dot_url', 'qty_hyphen_url', 'qty_underline_url', 'qty_slash_url',
       'qty_questionmark_url', 'qty_equal_url', 'qty_at_url', 'qty_and_url',
       'qty_exclamation_url', 'qty_space_url',
       ...
       'qty_ip_resolved', 'qty_nameservers', 'qty_mx_servers', 'ttl_hostname',
       'tls_ssl_certificate', 'qty_redirects', 'url_google_index',
       'domain_google_index', 'url_shortened', 'phishing'],
      dtype='object', length=112)
         qty_dot_url  qty_hyphen_url  qty_underline_url  qty_slash_url  \
count  129698.000000   129698.000000      129698.000000  129698.000000   
mean        2.220612        0.370044           0.132392       1.489892   
std         1.314717        1.199731           0.706240       1.963822   
min         1.000000        0.000000           0.000000       0.000000   
25%         2.000000        0.000000           0.000000       0.000000   
50%         2.000000        0.000000           0.000000       1.000000   
75%         2.0